config/routes.rb
Rails.application.routes.draw do
  get "/articles", to: "articles#index"
  resources :elves
  resources :dwarves
  resources :rogues
  resources :wizards
  get 'warriors/index'
  get 'warriors/jax'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/champions/', to: 'champions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dwarf.rb
class Dwarf < ApplicationRecord
end

app/models/elf.rb
class Elf < ApplicationRecord
end

app/models/rogue.rb
class Rogue < ApplicationRecord
end

app/models/warrior.rb
class Warrior < ApplicationRecord
end

app/models/wizard.rb
class Wizard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
    def index
    end
end

app/controllers/dwarves_controller.rb
class DwarvesController < ApplicationController
  before_action :set_dwarf, only: %i[ show edit update destroy ]

  # GET /dwarves or /dwarves.json
  def index
    @dwarves = Dwarf.all
  end

  # GET /dwarves/1 or /dwarves/1.json
  def show
  end

  # GET /dwarves/new
  def new
    @dwarf = Dwarf.new
  end

  # GET /dwarves/1/edit
  def edit
  end

  # POST /dwarves or /dwarves.json
  def create
    @dwarf = Dwarf.new(dwarf_params)

    respond_to do |format|
      if @dwarf.save
        format.html { redirect_to @dwarf, notice: "Dwarf was successfully created." }
        format.json { render :show, status: :created, location: @dwarf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dwarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dwarves/1 or /dwarves/1.json
  def update
    respond_to do |format|
      if @dwarf.update(dwarf_params)
        format.html { redirect_to @dwarf, notice: "Dwarf was successfully updated." }
        format.json { render :show, status: :ok, location: @dwarf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dwarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dwarves/1 or /dwarves/1.json
  def destroy
    @dwarf.destroy
    respond_to do |format|
      format.html { redirect_to dwarves_url, notice: "Dwarf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dwarf
      @dwarf = Dwarf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dwarf_params
      params.require(:dwarf).permit(:name, :height, :armor_class)
    end
end

app/controllers/elves_controller.rb
class ElvesController < ApplicationController
  before_action :set_elf, only: %i[ show edit update destroy ]

  # GET /elves or /elves.json
  def index
    @elves = Elf.all
  end

  # GET /elves/1 or /elves/1.json
  def show
  end

  # GET /elves/new
  def new
    @elf = Elf.new
  end

  # GET /elves/1/edit
  def edit
  end

  # POST /elves or /elves.json
  def create
    @elf = Elf.new(elf_params)

    respond_to do |format|
      if @elf.save
        format.html { redirect_to @elf, notice: "Elf was successfully created." }
        format.json { render :show, status: :created, location: @elf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elves/1 or /elves/1.json
  def update
    respond_to do |format|
      if @elf.update(elf_params)
        format.html { redirect_to @elf, notice: "Elf was successfully updated." }
        format.json { render :show, status: :ok, location: @elf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elves/1 or /elves/1.json
  def destroy
    @elf.destroy
    respond_to do |format|
      format.html { redirect_to elves_url, notice: "Elf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elf
      @elf = Elf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elf_params
      params.require(:elf).permit(:name, :level, :damage)
    end
end

app/controllers/rogues_controller.rb
class RoguesController < ApplicationController
  before_action :set_rogue, only: %i[ show edit update destroy ]

  # GET /rogues or /rogues.json
  def index
    @rogues = Rogue.all
  end

  # GET /rogues/1 or /rogues/1.json
  def show
  end

  # GET /rogues/new
  def new
    @rogue = Rogue.new
  end

  # GET /rogues/1/edit
  def edit
  end

  # POST /rogues or /rogues.json
  def create
    @rogue = Rogue.new(rogue_params)

    respond_to do |format|
      if @rogue.save
        format.html { redirect_to @rogue, notice: "Rogue was successfully created." }
        format.json { render :show, status: :created, location: @rogue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rogues/1 or /rogues/1.json
  def update
    respond_to do |format|
      if @rogue.update(rogue_params)
        format.html { redirect_to @rogue, notice: "Rogue was successfully updated." }
        format.json { render :show, status: :ok, location: @rogue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rogues/1 or /rogues/1.json
  def destroy
    @rogue.destroy
    respond_to do |format|
      format.html { redirect_to rogues_url, notice: "Rogue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rogue
      @rogue = Rogue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rogue_params
      params.require(:rogue).permit(:name, :weapon, :health)
    end
end

app/controllers/warriors_controller.rb
class WarriorsController < ApplicationController
  def index
  end
  def jax
  end
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
    def index
        @buyuculer=Wizard.all
    end
    def show
        @buyuculer2=Wizard.where(name:params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dwarves_helper.rb
module DwarvesHelper
end

app/helpers/elves_helper.rb
module ElvesHelper
end

app/helpers/rogues_helper.rb
module RoguesHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>

app/views/champions/index.html.erb
<html>
     <body>
<h1 id=header1 style="color:#FFFFFF; text-align: left;"><a href="https://www.milestone.submitapp.io" target="blank"> Ömer İnanç</a> </h1>

<h2 style="color:#FFFFFF;text-align: center;"> aka Yamasiro </h2>

<hr>
<main>
<style>
     .all-boxes{
          height: 500px;
          display: flex;
          justify-content: center;
     }
     .red-box{
          height: 400px;
          width: 400px;
          background-color: #9a1c23;
          border-radius: 100%;
          border: #000000;
          border-width: 5px;
          border-style: solid;
          align-self: center ;
     }
     .inside-box{
          height: 50%;
          width: 50%;
          background-color: #FFFFFF;
          border: #000000;
          border-radius: 100%;
          border-width: 20px;
          border-style: solid;
          margin: 80px 0px 0px 80px ;
     }
     .eyes{
          height: 50%;
          width: 50%;
          background-color: black;
          border-radius: 100%;
          padding: 0px -50px 0px -50px;
          margin-left: 14px;
          margin-top: 80px;
          margin-right: 75px;
     }
     .aqua-box{
          height: 400px;
          width: 400px;
          background-color: aqua;
          border-radius: 100%;
          border: #000000;
          border-width: 5px;
          border-style: solid;
          align-self: center;
     }
     .inside-aqua-box{
          height: 50%;
          width: 50%;
          background-color: #FFFFFF;
          border: #000000;
          border-radius: 100%;
          border-width: 20px;
          border-style: solid;
          margin: 100px 0px 0px 100px ;
     }
     .dashed-purple-background{
          background-color: #4a29c4; 
          border-style: dashed; 
          border-width: 5px;
     }
body {
    
	background-image: url(http://wallpaperswide.com/download/colorful_clouds_ocean-wallpaper-2560x1440.jpg);
	background-size: contain; 
     background-repeat: repeat;
     }
</style>
<!--
<img src="http://wallpaperswide.com/download/colorful_clouds_ocean-wallpaper-2560x1440.jpg">
-->
<div class="all-boxes">

     <div class="red-box">
          <div class="inside-box">
               <div class="eyes"></div>
          </div>
     </div>

     <div class="aqua-box">
          <div class="inside-box">
               <div class="eyes"></div>
          </div>
     </div>

</div>

<div style="text-align: center;">
<p style="color:#FFFFFF;">Click <a href="#footer1" style="color:#000000">here</a> to go to bottom of the page </p>

<p style="color:#FFFFFF">Click <a href="https://www.instagram.com/omeriinanc/" style="color:#000000"> here</a> to view my Instagram profile</p>
<p style="color:#FFFFFF">Click <a href="https://www.linkedin.com/in/ömer-inanç-8b8860170/" style="color:#000000"> Here</a> to view my LinkedIn profile</p> 
</div>
<hr>
<div class="dashed-purple-background" style="display: flex; flex-direction: row;">
     <div style="flex: 1; text-align: center;">
          <h3 style="color:#FFFFFF"> Down on your knees </h3>
          <p style="color:#FFFFFF">
               Last I saw you were down on your knees<br>Praying for some release<br><br>Check my bed but you ain't next to me<br>And I'm wondering where you ease<br>Bust until anyone let you know<br>But I don't understand this game<br>Bit my lip<br>But I said I would find<br>Something I didn't know I had
          </p>
     </div>
     <div style="flex: 1; text-align: center;">
          <h4 style="color:#FFFFFF"> Course </h4>
          <p style="color:#FFFFFF"> Almost winning and now I don't know<br>But It seems like It's almost away from me<br><br>Maybe one day I'll be strong enough to find it out<br>And I'll know it all
          </p>
     </div>
</div>
</main>

<hr>
<footer id="footer1" style="color:#FFFFFF; text-align: center;">
     All Right Deserved by Ömer İnanç - Click <a href="#header1" style="color:#ffffff">here</a> to go to top of the page 
    <form action="mailto:inanccomer@gmail.com">
        <input style="border:10px solid  #494343; margin-left: 20px; padding-right: 20px; padding-left:20px; " type="text" placeholder="Please Leave Me a Message" required>
        <button type="submit" style="border:10px solid #ffffff; border-radius: 5px; padding: 10px; color: #ffffff; background-color: #9a1c23;" hover="background-color:#9a1c23; color:#FFFFFF;" >Send</button>
   </form> 
</footer>
</body>
</html>

app/views/dwarves/_form.html.erb
<%= form_with(model: dwarf) do |form| %>
  <% if dwarf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dwarf.errors.count, "error") %> prohibited this dwarf from being saved:</h2>

      <ul>
        <% dwarf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label : %>
    <%= form.text_field : %>
  </div>

  <div class="field">
    <%= form.label : %>
    <%= form.text_field : %>
  </div>

  <div class="field">
    <%= form.label : %>
    <%= form.text_field : %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dwarves/edit.html.erb
<h1>Editing Dwarf</h1>

<%= render 'form', dwarf: @dwarf %>

<%= link_to 'Show', @dwarf %> |
<%= link_to 'Back', dwarves_path %>

app/views/dwarves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dwarves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>armor_class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dwarves.each do |dwarf| %>
      <tr>
        <td><%= dwarf.name %></td>
        <td><%= dwarf.height %></td>
        <td><%= dwarf.armor_class %></td>
        <td><%= link_to 'Show', dwarf %></td>
        <td><%= link_to 'Edit', edit_dwarf_path(dwarf) %></td>
        <td><%= link_to 'Destroy', dwarf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dwarf', new_dwarf_path %>

app/views/dwarves/new.html.erb
<h1>New Dwarf</h1>

<%= render 'form', dwarf: @dwarf %>

<%= link_to 'Back', dwarves_path %>

app/views/dwarves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @dwarf.name %>
</p>

<p>
  <strong>:</strong>
  <%= @dwarf.height %>
</p>

<p>
  <strong>:</strong>
  <%= @dwarf.armor_class %>
</p>

<%= link_to 'Edit', edit_dwarf_path(@dwarf) %> |
<%= link_to 'Back', dwarves_path %>

app/views/elves/_form.html.erb
<%= form_with(model: elf) do |form| %>
  <% if elf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elf.errors.count, "error") %> prohibited this elf from being saved:</h2>

      <ul>
        <% elf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :damage %>
    <%= form.number_field :damage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elves/edit.html.erb
<h1>Editing Elf</h1>

<%= render 'form', elf: @elf %>

<%= link_to 'Show', @elf %> |
<%= link_to 'Back', elves_path %>

app/views/elves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Damage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elves.each do |elf| %>
      <tr>
        <td><%= elf.name %></td>
        <td><%= elf.level %></td>
        <td><%= elf.damage %></td>
        <td><%= link_to 'Show', elf %></td>
        <td><%= link_to 'Edit', edit_elf_path(elf) %></td>
        <td><%= link_to 'Destroy', elf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elf', new_elf_path %>

app/views/elves/new.html.erb
<h1>New Elf</h1>

<%= render 'form', elf: @elf %>

<%= link_to 'Back', elves_path %>

app/views/elves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @elf.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @elf.level %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @elf.damage %>
</p>

<%= link_to 'Edit', edit_elf_path(@elf) %> |
<%= link_to 'Back', elves_path %>

app/views/rogues/_form.html.erb
<%= form_with(model: rogue) do |form| %>
  <% if rogue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rogue.errors.count, "error") %> prohibited this rogue from being saved:</h2>

      <ul>
        <% rogue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :weapon %>
    <%= form.text_field :weapon %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rogues/edit.html.erb
<h1>Editing Rogue</h1>

<%= render 'form', rogue: @rogue %>

<%= link_to 'Show', @rogue %> |
<%= link_to 'Back', rogues_path %>

app/views/rogues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rogues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weapon</th>
      <th>Health</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rogues.each do |rogue| %>
      <tr>
        <td><%= rogue.name %></td>
        <td><%= rogue.weapon %></td>
        <td><%= rogue.health %></td>
        <td><%= link_to 'Show', rogue %></td>
        <td><%= link_to 'Edit', edit_rogue_path(rogue) %></td>
        <td><%= link_to 'Destroy', rogue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rogue', new_rogue_path %>

app/views/rogues/new.html.erb
<h1>New Rogue</h1>

<%= render 'form', rogue: @rogue %>

<%= link_to 'Back', rogues_path %>

app/views/rogues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rogue.name %>
</p>

<p>
  <strong>Weapon:</strong>
  <%= @rogue.weapon %>
</p>

<p>
  <strong>Health:</strong>
  <%= @rogue.health %>
</p>

<%= link_to 'Edit', edit_rogue_path(@rogue) %> |
<%= link_to 'Back', rogues_path %>

app/views/warriors/index.html.erb
<h1>Warriors#index</h1>
<p>Find me in app/views/warriors/index.html.erb</p>

app/views/warriors/jax.html.erb
<!DOCTYPE html>
<html> 
<body>
<main>
hello
</main>
</body>
</html>

app/views/wizards/index.html.erb
<%= @buyuculer.pluck(:name,:spell_name)%>

app/views/wizards/show.html.erb
<%=@buyuculer2.pluck(:name,:spell_name)%>